# -*- coding: utf-8 -*-
"""tugas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LoDNPHzSE-82TKg4mn-5rXhzKD2rUGUl
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import spacy
import numpy as np
dataset = pd.read_csv('/content/drive/MyDrive/ANALISIS NARASI/IMDB Dataset.csv')
print (dataset)

nlp = spacy.load("en_core_web_sm")
hapus_kata = ["I", "a", "an", "the", "in", "on", " at", "with", "of", " for", "and", ".", ",", "br", "<", ">", "'m"]
def tokenize_dan_hapus_kata(text):
    doc = nlp(text)
    tokens = [tokens.text for tokens in doc if tokens.text.lower() not in hapus_kata and not tokens.is_stop]
    return tokens
dataset['tokens'] = dataset['review'].apply(tokenize_dan_hapus_kata)

print (dataset['tokens'])

from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
matx = vectorizer.fit_transform(dataset['tokens'])
words = vectorizer.get_feature_names_out()
word_frequencies = matx.toarray()


print (word_frequencies)



column_names = dataset.columns
print (column_names)

from sklearn.model_selection import train_test_split


X = dataset['review']
Y = dataset['sentiment']

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.10, random_state=2023)
X = np.array(X)
Y = np.array(Y)

print (X)
print (Y)

from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer()
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)

print (X_test_tfidf.shape)

from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train_tfidf, y_train)

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
y_pred = model.predict(X_test_tfidf)
accuracy = accuracy_score(y_test, y_pred)
print ("Accuracy : " + str(accuracy))
print (classification_report(y_test, y_pred))
print ("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))



"""# New Section"""